@extends('layouts.dashboard')
@section('title',$event->exists?'Editar evento':'Novo evento')
@section('content')
@php($input='mt-1 w-full rounded-xl border border-neutral-300 px-4 py-2.5 text-sm')
@php($tz=config('pindorama.timezone'))
@php($sessions=old('sessions',$event->exists?$event->sessions->map(fn($s)=>['title'=>$s->title,'starts_at'=>$s->starts_at->setTimezone($tz)->format('Y-m-d\TH:i'),'ends_at'=>$s->ends_at->setTimezone($tz)->format('Y-m-d\TH:i'),'room_id'=>$s->room_id,'location_label'=>$s->location_label,'meeting_link'=>$s->meeting_link])->all():[['title'=>'','starts_at'=>'','ends_at'=>'','room_id'=>'','location_label'=>'','meeting_link'=>'']]))
<div class="mx-auto max-w-4xl"><div class="mb-6 flex justify-between"><h1 class="text-2xl font-extrabold">{{ $event->exists?'Editar evento':'Novo evento' }}</h1><a href="{{ route('admin.events.index') }}" class="text-sm text-neutral-500">← Eventos</a></div>
@if($errors->any())<div class="mb-4 rounded-xl bg-red-50 p-4 text-sm text-red-700"><ul class="list-inside list-disc">@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div>@endif
<form method="POST" enctype="multipart/form-data" action="{{ $event->exists?route('admin.events.update',$event):route('admin.events.store') }}" class="space-y-5">@csrf @if($event->exists)@method('PUT')@endif
<div class="card grid gap-4 p-6 sm:grid-cols-2"><label class="text-sm sm:col-span-2">Título<input name="title" value="{{ old('title',$event->title) }}" required class="{{ $input }}"></label><label class="text-sm sm:col-span-2">Descrição<textarea name="description" rows="5" class="{{ $input }}">{{ old('description',$event->description) }}</textarea></label><label class="text-sm">Tipo<select name="type" class="{{ $input }}">@foreach(\App\Models\Event::TYPES as $v=>$l)<option value="{{ $v }}" @selected(old('type',$event->type)===$v)>{{ $l }}</option>@endforeach</select></label><label class="text-sm">Modalidade<select name="modality" class="{{ $input }}"><option value="presencial" @selected(old('modality',$event->modality)==='presencial')>Presencial</option><option value="online" @selected(old('modality',$event->modality)==='online')>Online</option></select></label><label class="text-sm">Local geral<input name="location_label" value="{{ old('location_label',$event->location_label) }}" class="{{ $input }}"></label><label class="text-sm">Sala principal<select name="room_id" class="{{ $input }}"><option value="">Sem sala</option>@foreach($rooms as $room)<option value="{{ $room->id }}" @selected(old('room_id',$event->room_id)==$room->id)>{{ $room->name }}</option>@endforeach</select></label><label class="text-sm">Capa/banner<input type="file" name="cover" accept="image/*" class="{{ $input }}"></label><label class="text-sm">Status<select name="status" class="{{ $input }}">@foreach(\App\Models\Event::STATUSES as $v=>$l)<option value="{{ $v }}" @selected(old('status',$event->status)===$v)>{{ $l }}</option>@endforeach</select></label></div>
<div class="card p-6"><h2 class="font-bold">Instrutores</h2><p class="mb-3 text-xs text-neutral-500">Todos precisam possuir perfil profissional ativo.</p><div class="grid gap-2 sm:grid-cols-2">@php($selected=old('instructors',$event->exists?$event->instructors->pluck('id')->all():[]))@foreach($professionals as $professional)<label class="flex items-center gap-2 rounded-lg border p-3 text-sm"><input type="checkbox" name="instructors[]" value="{{ $professional->id }}" @checked(in_array($professional->id,$selected))>{{ $professional->display_name }}</label>@endforeach</div></div>
<div class="card p-6"><div class="flex justify-between"><div><h2 class="font-bold">Encontros</h2><p class="text-xs text-neutral-500">Cursos podem ter várias datas.</p></div><button type="button" id="add-session" class="btn-outline">Adicionar encontro</button></div><div id="sessions" class="mt-4 space-y-4">@foreach($sessions as $i=>$session)<div class="session grid gap-3 rounded-xl border p-4 sm:grid-cols-2"><label class="text-sm">Nome do encontro<input name="sessions[{{ $i }}][title]" value="{{ $session['title'] }}" class="{{ $input }}"></label><label class="text-sm">Sala<select name="sessions[{{ $i }}][room_id]" class="{{ $input }}"><option value="">Sem sala</option>@foreach($rooms as $room)<option value="{{ $room->id }}" @selected(($session['room_id']??null)==$room->id)>{{ $room->name }}</option>@endforeach</select></label><label class="text-sm">Início<input type="datetime-local" name="sessions[{{ $i }}][starts_at]" value="{{ $session['starts_at'] }}" required class="{{ $input }}"></label><label class="text-sm">Término<input type="datetime-local" name="sessions[{{ $i }}][ends_at]" value="{{ $session['ends_at'] }}" required class="{{ $input }}"></label><label class="text-sm">Local<input name="sessions[{{ $i }}][location_label]" value="{{ $session['location_label']??'' }}" class="{{ $input }}"></label><label class="text-sm">Link online<input type="url" name="sessions[{{ $i }}][meeting_link]" value="{{ $session['meeting_link']??'' }}" class="{{ $input }}"></label><button type="button" class="remove-session text-left text-xs text-red-600">Remover encontro</button></div>@endforeach</div></div>
<div class="card grid gap-4 p-6 sm:grid-cols-3"><label class="text-sm">Vagas (0 ilimitado)<input type="number" min="0" name="capacity" value="{{ old('capacity',$event->capacity??0) }}" class="{{ $input }}"></label><label class="text-sm">Preço<input type="number" step=".01" min="0" name="price" value="{{ old('price',$event->price??0) }}" class="{{ $input }}"></label><label class="text-sm">Desconto %<input type="number" step=".01" min="0" max="100" name="discount_percent" value="{{ old('discount_percent',$event->discount_percent??0) }}" class="{{ $input }}"></label><label class="text-sm">Casa %<input type="number" step=".01" min="0" max="100" name="house_percentage" value="{{ old('house_percentage',$event->house_percentage??0) }}" class="{{ $input }}"></label><label class="text-sm">Lembrete (h)<input type="number" min="0" max="168" name="reminder_hours" value="{{ old('reminder_hours',$event->reminder_hours??24) }}" class="{{ $input }}"></label><div class="flex items-end gap-4"><label class="text-sm"><input type="checkbox" name="is_free" value="1" @checked(old('is_free',$event->is_free))> Gratuito</label><label class="text-sm"><input type="checkbox" name="allow_discount" value="1" @checked(old('allow_discount',$event->allow_discount))> Aplicar desconto</label></div></div>
<div class="card p-5"><label class="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" name="force_conflict" value="1"> Forçar conflito excepcional</label><input name="override_reason" placeholder="Justificativa obrigatória para a exceção" class="{{ $input }}"></div><div class="text-right"><button class="btn-brand">Salvar evento</button></div></form>
@if($event->exists)<form method="POST" action="{{ route('admin.events.destroy',$event) }}" onsubmit="return confirm('Remover este evento?')" class="mt-4 text-right">@csrf @method('DELETE')<button class="text-sm text-red-600">Remover evento</button></form>@endif</div>
<template id="session-template"><div class="session grid gap-3 rounded-xl border p-4 sm:grid-cols-2"><label class="text-sm">Nome do encontro<input data-name="title" class="{{ $input }}"></label><label class="text-sm">Sala<select data-name="room_id" class="{{ $input }}"><option value="">Sem sala</option>@foreach($rooms as $room)<option value="{{ $room->id }}">{{ $room->name }}</option>@endforeach</select></label><label class="text-sm">Início<input type="datetime-local" data-name="starts_at" required class="{{ $input }}"></label><label class="text-sm">Término<input type="datetime-local" data-name="ends_at" required class="{{ $input }}"></label><label class="text-sm">Local<input data-name="location_label" class="{{ $input }}"></label><label class="text-sm">Link online<input type="url" data-name="meeting_link" class="{{ $input }}"></label><button type="button" class="remove-session text-left text-xs text-red-600">Remover encontro</button></div></template>
<script>const box=document.getElementById('sessions');let sessionIndex={{ count($sessions) }};function bind(){box.querySelectorAll('.remove-session').forEach(b=>b.onclick=()=>{if(box.children.length>1)b.closest('.session').remove()})}document.getElementById('add-session').onclick=()=>{const node=document.getElementById('session-template').content.cloneNode(true),i=sessionIndex++;node.querySelectorAll('[data-name]').forEach(el=>el.name=`sessions[${i}][${el.dataset.name}]`);box.appendChild(node);bind()};bind()</script>
@endsection
