@extends('layouts.dashboard')
@section('title','Agendar cliente')
@section('content')
@php($input='mt-1 w-full rounded-xl border border-neutral-300 px-4 py-2.5 text-sm')
<div class="mx-auto max-w-2xl"><div class="flex justify-between"><div><h1 class="text-2xl font-extrabold">Agendar em nome do cliente</h1><p class="mt-1 text-sm text-neutral-500">O horário será validado contra disponibilidade, consultas e eventos.</p></div><a href="{{ $root?route('admin.customers.create'):route('professional.customers.create') }}" class="btn-outline self-start">Novo cliente</a></div>
@if($errors->any())<div class="mt-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ $root?route('admin.bookings.store'):route('professional.bookings.store') }}" class="card mt-5 grid gap-4 p-6 sm:grid-cols-2">@csrf
<label class="text-sm sm:col-span-2">Cliente<select name="customer_id" required class="{{ $input }}"><option value="">Selecione</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected(old('customer_id')==$customer->id)>{{ $customer->name }} · {{ $customer->email }}</option>@endforeach</select></label>
<label class="text-sm sm:col-span-2">Serviço<select id="service" name="service_id" required class="{{ $input }}"><option value="">Selecione</option>@foreach($services as $service)<option value="{{ $service->id }}" data-locations='@json($service->locations->map(fn($l)=>['id'=>$l->id,'label'=>$l->name])->values())' @selected(old('service_id')==$service->id)>{{ $service->title }} · {{ $service->professional->display_name }} · {{ money($service->price) }}</option>@endforeach</select></label>
<label class="text-sm">Local<select id="location" name="attendance_location_id" required class="{{ $input }}"><option value="">Escolha o serviço</option></select></label><label class="text-sm">Data e hora<input type="datetime-local" name="start_at" value="{{ old('start_at') }}" required class="{{ $input }}"></label><label class="text-sm">Telefone<input name="patient_phone" value="{{ old('patient_phone') }}" class="{{ $input }}"></label><label class="flex items-end gap-2 pb-2 text-sm"><input type="checkbox" name="mark_paid" value="1" @checked(old('mark_paid'))> Pagamento recebido manualmente</label><label class="text-sm sm:col-span-2">Observações<textarea name="notes" rows="3" class="{{ $input }}">{{ old('notes') }}</textarea></label><label class="flex items-start gap-2 text-xs text-neutral-600 sm:col-span-2"><input type="checkbox" name="health_data_consent" value="1" required class="mt-0.5"> O cliente autorizou o registro e tratamento destes dados para o atendimento.</label><div class="sm:col-span-2 text-right"><button class="btn-brand">Confirmar agendamento</button></div></form></div>
<script>const service=document.getElementById('service'),locationEl=document.getElementById('location');function locations(){const opt=service.selectedOptions[0],list=opt?.dataset.locations?JSON.parse(opt.dataset.locations):[];locationEl.innerHTML='<option value="">Selecione</option>'+list.map(l=>`<option value="${l.id}">${l.label}</option>`).join('');const old=@json(old('attendance_location_id'));if(old)locationEl.value=old}service.addEventListener('change',locations);locations()</script>
@endsection
