@extends('layouts.dashboard')
@section('title','Financeiro global')
@section('content')
<div class="space-y-6"><div class="flex flex-wrap items-center justify-between gap-3"><div><h1 class="text-2xl font-extrabold">Financeiro global</h1><p class="text-sm text-neutral-500">Serviços, eventos, valores da casa e repasses.</p></div><div class="flex gap-2"><a href="{{ route('admin.payments.export',request()->query()) }}" class="btn-outline">Exportar CSV</a><a href="{{ route('admin.payments.pdf',request()->query()) }}" class="btn-outline">Exportar PDF</a></div></div>
<div class="card p-4 text-sm"><span class="chip {{ $config['enabled']?'bg-brand-100 text-brand-800':'bg-neutral-200' }}">{{ $config['enabled']?'Mercado Pago ativo · '.$config['environment']:'Mercado Pago desligado · simulação' }}</span></div>
<form method="GET" class="card grid gap-3 p-4 sm:grid-cols-6"><select name="professional_id" class="rounded-lg border px-3 py-2 text-sm"><option value="">Todos os profissionais</option>@foreach($professionals as $p)<option value="{{ $p->id }}" @selected(request('professional_id')==$p->id)>{{ $p->display_name }}</option>@endforeach</select><select name="type" class="rounded-lg border px-3 py-2 text-sm"><option value="">Serviços e eventos</option><option value="appointment" @selected(request('type')==='appointment')>Serviços</option><option value="event" @selected(request('type')==='event')>Eventos</option></select><select name="status" class="rounded-lg border px-3 py-2 text-sm"><option value="">Todos os status</option>@foreach(['pending','in_process','approved','authorized','rejected','refunded','cancelled'] as $s)<option value="{{ $s }}" @selected(request('status')===$s)>{{ $s }}</option>@endforeach</select><input type="date" name="from" value="{{ request('from') }}" class="rounded-lg border px-3 py-2 text-sm"><input type="date" name="to" value="{{ request('to') }}" class="rounded-lg border px-3 py-2 text-sm"><button class="btn-outline">Filtrar</button></form>
<div class="grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-7">@foreach([['Aprovados',$totals['approved']],['Pendentes',$totals['pending']],['Receita',money($totals['revenue'])],['Casa',money($totals['commission'])],['Profissionais',money($totals['professional'])],['Taxas plataforma',money($totals['platform_charges'])],['Repassado',money($totals['paid_out'])]] as [$l,$v])<div class="card p-4"><p class="text-xs uppercase text-neutral-400">{{ $l }}</p><p class="mt-1 font-extrabold">{{ $v }}</p></div>@endforeach</div>
<div class="card overflow-x-auto"><table class="w-full text-sm"><thead><tr class="border-b text-left text-xs uppercase text-neutral-400"><th class="p-3">Referência</th><th>Origem</th><th>Profissional</th><th>Bruto</th><th>Casa</th><th>Líquido</th><th>Status</th></tr></thead><tbody>@forelse($transactions as $tx)<tr class="border-b"><td class="p-3 font-mono text-xs">{{ $tx->reference }}</td><td>{{ $tx->payable instanceof \App\Models\Appointment?'Serviço':'Evento' }}</td><td>{{ $tx->professional?->display_name }}</td><td>{{ money($tx->gross_amount) }}</td><td>{{ money($tx->house_amount) }}</td><td>{{ money($tx->professional_amount) }}</td><td><span class="chip bg-neutral-100">{{ $tx->status }}</span></td></tr>@empty<tr><td colspan="7" class="p-6 text-center text-neutral-500">Nenhuma transação.</td></tr>@endforelse</tbody></table></div><div>{{ $transactions->links() }}</div>
<div class="grid gap-5 lg:grid-cols-2"><form method="POST" action="{{ route('admin.payouts.store') }}" class="card grid gap-3 p-5 sm:grid-cols-2">@csrf<h2 class="font-bold sm:col-span-2">Registrar repasse</h2><select name="professional_id" required class="rounded-lg border px-3 py-2 text-sm"><option value="">Profissional</option>@foreach($professionals as $p)<option value="{{ $p->id }}">{{ $p->display_name }}</option>@endforeach</select><input type="number" step=".01" min=".01" name="amount" placeholder="Valor" required class="rounded-lg border px-3 py-2 text-sm"><input type="date" name="period_start" required class="rounded-lg border px-3 py-2 text-sm"><input type="date" name="period_end" required class="rounded-lg border px-3 py-2 text-sm"><textarea name="notes" placeholder="Observações" class="rounded-lg border px-3 py-2 text-sm sm:col-span-2"></textarea><button class="btn-brand sm:col-span-2">Registrar</button></form><div class="card p-5"><h2 class="mb-3 font-bold">Repasses recentes</h2><div class="space-y-2">@forelse($payouts as $payout)<div class="flex items-center justify-between rounded-lg border p-3 text-sm"><div><p class="font-semibold">{{ $payout->professional?->display_name }} · {{ money($payout->amount) }}</p><p class="text-xs text-neutral-500">{{ $payout->period_start->format('d/m/Y') }}–{{ $payout->period_end->format('d/m/Y') }} · {{ $payout->status }}</p></div>@if($payout->status==='pending')<form method="POST" action="{{ route('admin.payouts.status',$payout) }}">@csrf<input type="hidden" name="status" value="paid"><button class="text-brand-700">Marcar pago</button></form>@endif</div>@empty<p class="text-sm text-neutral-500">Nenhum repasse.</p>@endforelse</div></div></div></div>
@endsection
