@extends('layouts.dashboard')
@section('title', $user->exists ? 'Editar profissional' : 'Novo profissional')
@section('content')
@php($input='mt-1 w-full rounded-xl border border-neutral-300 px-4 py-2.5 text-sm')
<div class="mx-auto max-w-3xl"><div class="mb-6 flex items-center justify-between"><div><h1 class="text-2xl font-extrabold">{{ $user->exists?'Editar profissional':'Novo profissional' }}</h1><p class="text-sm text-neutral-500">Identidade visual e fontes seguem o padrão global do site.</p></div><a href="{{ route('admin.professionals.index') }}" class="text-sm text-neutral-500">← Voltar</a></div>
@if($errors->any())<div class="mb-4 rounded-xl bg-red-50 p-4 text-sm text-red-700"><ul class="list-inside list-disc">@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div>@endif
<form method="POST" enctype="multipart/form-data" action="{{ $user->exists?route('admin.professionals.update',$user):route('admin.professionals.store') }}" class="card space-y-6 p-6">@csrf @if($user->exists)@method('PUT')@endif
<section><h2 class="font-bold">Acesso</h2><div class="mt-3 grid gap-4 sm:grid-cols-2"><label class="text-sm">Nome civil<input name="name" value="{{ old('name',$user->name) }}" required class="{{ $input }}"></label><label class="text-sm">E-mail<input type="email" name="email" value="{{ old('email',$user->email) }}" required class="{{ $input }}"></label></div></section>
<section><h2 class="font-bold">Landing page</h2><div class="mt-3 grid gap-4 sm:grid-cols-2"><label class="text-sm">Nome público<input name="professional_name" value="{{ old('professional_name',$user->professional_name) }}" required class="{{ $input }}"></label><label class="text-sm">Título/chamada<input name="headline" value="{{ old('headline',$user->headline) }}" class="{{ $input }}"></label><label class="text-sm sm:col-span-2">Biografia<textarea name="bio" rows="5" class="{{ $input }}">{{ old('bio',$user->bio) }}</textarea></label><label class="text-sm">Cidade<input name="city" value="{{ old('city',$user->city) }}" class="{{ $input }}"></label><label class="text-sm">Estado<input name="state" value="{{ old('state',$user->state) }}" class="{{ $input }}"></label><label class="text-sm">Telefone<input name="phone" value="{{ old('phone',$user->phone) }}" class="{{ $input }}"></label><label class="text-sm">WhatsApp<input name="whatsapp" value="{{ old('whatsapp',$user->whatsapp) }}" class="{{ $input }}"></label><label class="text-sm">Registro profissional<input name="registration_council" value="{{ old('registration_council',$user->registration_council) }}" class="{{ $input }}"></label><label class="text-sm">Fuso horário<input name="timezone" value="{{ old('timezone',$user->timezone ?: config('pindorama.timezone')) }}" required class="{{ $input }}"></label><label class="text-sm">Foto<input type="file" name="avatar" accept="image/*" class="{{ $input }}"></label><label class="text-sm">Banner superior<input type="file" name="banner" accept="image/*" class="{{ $input }}"></label></div></section>
<section><h2 class="font-bold">Redes sociais</h2><div class="mt-3 grid gap-4 sm:grid-cols-2">@foreach(['instagram_url'=>'Instagram','facebook_url'=>'Facebook','youtube_url'=>'YouTube','website_url'=>'Site pessoal'] as $field=>$label)<label class="text-sm">{{ $label }}<input type="url" name="{{ $field }}" value="{{ old($field,$user->{$field}) }}" placeholder="https://" class="{{ $input }}"></label>@endforeach</div></section>
<section><h2 class="font-bold">Práticas cadastradas</h2><div class="mt-3 grid gap-2 sm:grid-cols-2">@foreach($categories as $category)<label class="flex items-center gap-2 rounded-lg border p-2 text-sm"><input type="checkbox" name="specialties[]" value="{{ $category->id }}" @checked(in_array($category->id,old('specialties',$selectedSpecialties)))>{{ $category->name }}</label>@endforeach</div></section>
<div class="text-right"><button class="btn-brand">{{ $user->exists?'Salvar alterações':'Criar e enviar convite' }}</button></div></form></div>
@endsection
